### ISSUE TITLE
Sanity tests failing in netapp.um_info

### ISSUE THREAD

**Issue by dmsimard** [ansible-collections/netapp.um_info#7]
### Summary

We are running sanity tests across every collection included in the Ansible community package (as part of [this issue](https://github.com/ansible-community/community-topics/issues/96)) and found that ``ansible-test sanity --docker`` against netapp.um_info 21.8.0 fails with ansible-core 2.13.0rc1 in ansible 6.0.0a2.

### Component Name

n/a

### Ansible Version

```console
ansible [core 2.13.0rc1]
```

### UM_Info Collection Version

```console
21.8.0
```

### Playbook

```console
n/a
```

### Steps to Reproduce

```yaml (paste below)
ansible-test sanity --docker
```

### Expected Results

Tests are either passing or ignored.

### Actual Results

```console
ERROR: Found 5 validate-modules issue(s) which need to be resolved:
ERROR: plugins/modules/na_um_list_aggregates.py:0:0: invalid-documentation: DOCUMENTATION.module: not a valid value for dictionary value @ data['module']. Got 'na_um_aggregates_info'
ERROR: plugins/modules/na_um_list_clusters.py:0:0: invalid-documentation: DOCUMENTATION.module: not a valid value for dictionary value @ data['module']. Got 'na_um_clusters_info'
ERROR: plugins/modules/na_um_list_nodes.py:0:0: invalid-documentation: DOCUMENTATION.module: not a valid value for dictionary value @ data['module']. Got 'na_um_nodes_info'
ERROR: plugins/modules/na_um_list_svms.py:0:0: invalid-documentation: DOCUMENTATION.module: not a valid value for dictionary value @ data['module']. Got 'na_um_svms_info'
ERROR: plugins/modules/na_um_list_volumes.py:0:0: invalid-documentation: DOCUMENTATION.module: not a valid value for dictionary value @ data['module']. Got 'na_um_volumes_info'
ERROR: The 1 sanity test(s) listed below (out of 43) failed. See error output above for details.
validate-modules
ERROR: Command "podman exec ansible-test-controller-3TCcCiM8 /usr/bin/env ANSIBLE_TEST_CONTENT_ROOT=/root/ansible_collections/netapp/um_info LC_ALL=en_US.UTF-8 /usr/bin/python3.10 /root/ansible/bin/ansible-test sanity --containers '{}' --skip-test pylint --metadata tests/output/.tmp/metadata-l5lp5x76.json --truncate 0 --color no --host-path tests/output/.tmp/host-j7cle0v0" returned exit status 1.
```

**Comment by lonico** [comment]
We don't see these errors in our pipelines or in GitHub actions.  Is this a new checker?


We renamed the modules from na_um_list_XXXXX to na_um_XXXXX_info.   This was a request from RedHat to have a consistent naming:
eg: na_um_list_aggregates is now na_um_aggregates_info


We kept the old modules as deprecated, but they are symlinks to the new ones.   Hence the difference between the name of the file (old name) and the module: name in the documentation section.

Should we address this with an exception?   Or maybe it's time to delete the older modules (the symlinks).

**Comment by mariolenz** [comment]
@lonico We're sorry, this looks like a false positive from our side. You can close this issue. If you're interested in what went wrong, see [here](https://github.com/ansible-community/community-topics/issues/96#issuecomment-1125572846) for more information.

**Comment by lonico** [comment]
No worries :)
